[package]
edition = "2021"
name = "wgpu"
version = "0.1.0"

[[bin]]
name = "wgpu"
path = "src/main.rs"


[dependencies]
env_logger = "0.10"
log = "0.4"
wgpu = "0.18"
winit = "0.28"
bytemuck = { version = "1.12", features = [ "derive" ] }


tokio = { workspace = true }
