[package]
name = "test_engine"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "test_engine"
crate-type = ["rlib", "staticlib"]

[dependencies]
#rand = "0.8.3"

#fontdue = "0.4.0"
#
chrono = "0.4.19"
lazy_static = "1.4.0"

gm = { path = "../gm" }
ui = { path = "../ui" }
image = { path = "../image" }
sprites = { path = "../sprites" }
gl_wrapper = { path = "../gl_wrapper" }
tools = { path = "../.rdeps/tools" }
rapier2d = { version = "0.9.2", features = [ "parallel", "simd-stable" ] }


[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = "0.14.0"
glfw = "0.41.0"

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
mashup = "0.1.12"
gles31-sys = { path = "../.rdeps/gles31-sys" }