[package]
name = "test_engine"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "test_engine"
crate-type = ["rlib", "staticlib"]

[dependencies]
log = "0.4"
home = "0.5"
rtools = "0.1.26"
reflected = "0.2.5"
smart-default = "0.6"

tokio = { version = "1.21", features = ["full"] }

gm = { path = "../deps/gm" }
rest = { path = "../deps/rest" }
text = { path = "../deps/text" }
maze = { path = "../deps/maze" }
audio = { path = "../deps/audio" }
valid = { path = "../deps/valid" }
sprites = { path = "../deps/sprites" }
dispatch = { path = "../deps/dispatch" }
gl_image = { path = "../deps/gl_image" }
gl_wrapper = { path = "../deps/gl_wrapper" }

ui = { path = "../deps/ui" }
ui_views = { path = "../deps/ui/ui_views" }

[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = "0.14"
glfw = "0.45"

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
mashup = "0.1"
gles31-sys = { path = "../gles31-sys" }

[build-dependencies]
cfg_aliases = "0.1"
