[package]
name = "test_engine"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "test_engine"
crate-type = ["rlib", "staticlib"]

[dependencies]
log = "0.4"
home = "0.5"
cfg-if = "1.0"
lazy_static = "1.4"
tokio = { version = "1.15", features = ["full"] }

rtools = { path = "../rtools" }

gm = { path = "../deps/gm" }
ui = { path = "../deps/ui" }
net = { path = "../deps/net" }
maze = { path = "../deps/maze" }
audio = { path = "../deps/audio" }
sprites = { path = "../deps/sprites" }
gl_image = { path = "../deps/gl_image" }
gl_wrapper = { path = "../deps/gl_wrapper" }

[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = "0.14"
glfw = "0.43"

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
mashup = "0.1"
gles31-sys = { path = "../gles31-sys" }

[build-dependencies]
cfg_aliases = "0.1"
