[package]
name = "test_engine"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "test_engine"
crate-type = ["rlib", "staticlib"]

[dependencies]
log = "0"
cfg-if = "1"
chrono = "0"

tools = { path = "../.rdeps/tools" }

gm = { path = "../gm" }
ui = { path = "../ui" }
maze = { path = "../maze" }
sprites = { path = "../sprites" }
gl_image = { path = "../gl_image" }
gl_wrapper = { path = "../gl_wrapper" }

[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = "0"
glfw = "0"

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
mashup = "0"
gles31-sys = { path = "../.rdeps/gles31-sys" }
