[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "wgpu_image"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "wgpu_image"

[dependencies]
anyhow = { workspace = true }
image = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }

manage = { workspace = true }
refs = { workspace = true }
rtools = { workspace = true }

gm = { workspace = true }
