[package]
edition = "2021"
name = "ui_proc_debug"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
derivative = { workspace = true }
log = { workspace = true }
itertools = { workspace = true }
smart-default = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }

dispatch = { workspace = true }
gl_image = { workspace = true }
gl_wrapper = { workspace = true }
gm = { workspace = true }
reflected = { workspace = true }
refs = { workspace = true }
rtools = { workspace = true }
text = { workspace = true }
ui = { workspace = true }
ui_views = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
