language: rust
matrix:
  include:
    - os: osx
    - os: windows
    - os: linux
      addons:
        apt:
          packages:
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev