[workspace]

members = [
    "rtools",
    "test_game",
    "test_engine",
    "deps/gm",
    "deps/ui",
    "deps/maze",
    "deps/audio",
    "deps/sprites",
    "deps/gl_image",
    "deps/gl_wrapper",
]

default-members = ["test_game"]
