[workspace]

default-members = ["test-game"]
members = ["test-engine", "test-game", "ui-test", "ui-benchmark"]

resolver = "2"

[workspace.metadata.cargo-machete]
ignored = []

[workspace.dependencies]
anyhow = "1.0"
bytemuck = { version = "1.15", features = ["derive"] }
cfg_aliases = "0.2"
chrono = "0.4"
dirs = "5.0"
educe = "0.5"
env_logger = "0.11"
fake = "2.9.2"
home = "0.5"
image = "0.25"
log = "0.4"
nonempty = "0.10.0"
rand = "0.8"
rapier2d = { version = "0.19.0", features = ["parallel", "simd-stable"] }
#rapier2d = { version = "0.19.0", features = ["enhanced-determinism"] }
convert_case = "0.6"
rodio = "0.18.0"
rust_decimal = "1.35"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serial_test = "3.1"
smart-default = "0.7.1"
tokio = { version = "1.37.0", features = ["full"] }
web-time = "1.0.0"

glyph_brush = "0.7.8"
wgpu = "0.20.0"
wgpu_text = "0.8.8"
winit = "0.29.15"

manage = "=0.4.10"
reflected = "=0.9.0"
refs = { version = "=0.8.2", default-features = true }
vents = "=0.5.0"

audio = { path = "deps/audio" }
call_counter = { path = "deps/call_counter" }
dispatch = { path = "deps/dispatch" }
gen = { path = "deps/gen" }
gm = { path = "deps/gm" }
level = { path = "deps/level" }
store = { path = "deps/store" }
test-engine = { path = "test-engine" }
ui = { path = "deps/ui" }
ui_proc = { path = "deps/ui/ui_proc" }
valid = { path = "deps/valid" }
wgpu_wrapper = { path = "deps/wgpu_wrapper" }
