[package]
name = "test_game"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[[bin]]
name = "test_game"

[lib]
name = "test_game_lib"
crate-type = ["rlib", "staticlib", "dylib"]

[dependencies]
log = "0.4"
rtools = "0.1.24"

tokio = { version = "1.21", features = ["full"] }

test_engine = { path = "test_engine" }

ui = { path = "deps/ui" }
ui_views = { path = "deps/ui/ui_views" }

[target.'cfg(target_os="android")'.dependencies]
android-ndk-sys = "0.2"

[build-dependencies]
cfg_aliases = "0.1"
