[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "test_game"
version = "0.1.0"

[[bin]]
name = "test_game"

[lib]
crate-type = ["rlib", "staticlib", "dylib"]
name = "test_game_lib"

[dependencies]
tokio = { workspace = true }

derivative = { workspace = true }
rtools = { workspace = true }
test_engine = { workspace = true }
ui = { workspace = true }
ui_views = { workspace = true }

[target.'cfg(target_os="android")'.dependencies]
android-ndk-sys = "0.2"

[build-dependencies]
cfg_aliases = { workspace = true }

[workspace.dependencies]
actix-web = { version = "4.3.1", default-features = false, features = ["rustls", "macros"] }
cfg-if = "1.0"
cfg_aliases = "0.1"
chrono = "0.4.24"
derivative = "2.2.0"
gl = "0.14"
glfw = "0.52.0"
home = "0.5.5"
log = "0.4"
mashup = "0.1"
itertools = "0.10.5"
reqwest = { version = "0.11.18", default-features = false, features = ["native-tls-vendored"] }
rust_decimal = "1.29.1"
nonempty = "0.8.1"
sea-orm = { version = "0.11.3", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serial_test = "2.0.0"
smart-default = "0.6"
tokio = { version = "1.26.0", features = ["full"] }


reflected = "0.7.0"
reflected_proc = "0.7.0"
refs = "0.2.7"
rtools = "0.3.0"
vents = "0.2.1"


audio = { path = "deps/audio" }
dispatch = { path = "deps/dispatch" }
gl_image = { path = "deps/gl_image" }
gl_wrapper = { path = "deps/gl_wrapper" }
gles31-sys = { path = "gles31-sys" }
gm = { path = "deps/gm" }
maze = { path = "deps/maze" }
rest = { path = "deps/rest" }
sprites = { path = "deps/sprites" }
test_engine = { path = "test_engine" }
text = { path = "deps/text" }
ui = { path = "deps/ui" }
ui_proc = { path = "deps/ui/ui_proc" }
ui_views = { path = "deps/ui/ui_views" }
valid = { path = "deps/valid" }
