[workspace]

default-members = ["test_game"]
members = ["test_game", "ui_test", "ui_benchmark", "noise", "wgpu_test"]

resolver = "2"

[workspace.dependencies]
anyhow = "1.0.75"
bytemuck = { version = "1.14", features = ["derive"] }
cfg_aliases = "0.2"
chrono = "0.4.24"
derivative = "2.2.0"
env_logger = "0.11.0"
gl = "0.14"
glfw = "0.54.0"
home = "0.5.5"
image = "0.24"
itertools = "0.12.0"
log = "0.4"
mashup = "0.1"
nonempty = "0.9.0"
rapier2d = { version = "0.18.0", features = ["parallel", "simd-stable"] }
reqwest = { version = "0.11.18", default-features = false, features = ["native-tls-vendored"] }
rust_decimal = "1.29.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serial_test = "3.0"
smart-default = "0.7.1"
tokio = { version = "1.33.0", features = ["full"] }
wgpu = "0.19.1"
winit = "0.29.10"

manage = "0.3.0"
reflected = "=0.7.0"
reflected_proc = "=0.7.0"
refs = { version = "=0.6.14", features = [] }
rtools = "=0.7.0"
vents = "=0.4.0"


audio = { path = "deps/audio" }
dispatch = { path = "deps/dispatch" }
gen = { path = "deps/gen" }
gl_image = { path = "deps/gl_image" }
wgpu_image = { path = "deps/wgpu_image" }
wgpu_wrapper = { path = "deps/wgpu_wrapper" }
gl_wrapper = { path = "deps/gl_wrapper" }
gles31-sys = { path = "gles31-sys" }
gm = { path = "deps/gm" }
rest = { path = "deps/rest" }
sprites = { path = "deps/sprites" }
test_engine = { path = "test_engine" }
test_game = { path = "test_game" }
text = { path = "deps/text" }
ui = { path = "deps/ui" }
ui_proc = { path = "deps/ui/ui_proc" }
ui_proc_debug = { path = "deps/ui/ui_proc_debug" }
ui_views = { path = "deps/ui/ui_views" }
valid = { path = "deps/valid" }
