[package]
name = "test_engine"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "test_engine"

[[bin]]
name = "test_engine"

[dependencies]
num = "0.4.0"
rand = "0.8.3"
guard = "0.5.0"
cfg-if = "1.0.0"
fontdue = "0.4.0"
derivative = "2.2.0"

tools = { path = ".rdeps/tools" }
soil2 = { path = ".rdeps/soil2" }


[target.'cfg(not(target_os="ios"))'.dependencies]
gl = "0.14.0"
glfw = "0.41.0"

[target.'cfg(target_os="ios")'.dependencies]
gles31-sys = { path = ".rdeps/gles31-sys" }
