[package]
name = "test_engine"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "test_engine"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "test_engine"

[dependencies]
num = "0.4.0"
rand = "0.8.3"
guard = "0.5.0"
image = "0.23.14"
serde = "1.0.126"
cfg-if = "1.0.0"
fontdue = "0.4.0"
rapier2d = "0.9.2"
derivative = "2.2.0"
lazy_static = "1.4.0"

tools = { path = ".rdeps/tools" }


[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = "0.14.0"
glfw = "0.41.0"
soil2 = { path = ".rdeps/soil2" }

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
mashup = "0.1.12"
gles31-sys = { path = ".rdeps/gles31-sys" }
