[package]
name = "untitled"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.41.0"
rand = "0.8.3"
regex = "1.4.5"
guard = "0.5.0"
assimp = "0.3.1"
derivative = "2.2.0"
num-traits = "0.2.14"
freetype-sys = "0.14.0"
rustc-serialize = "0.3.24"
