[workspace]

# default-members = ["level-test"]
#default-members = ["ui-test"]
default-members = ["test-game"]
members = [
  "test-engine",
  "test-game",
  "test-game-android",
  "ui-test",
  "ui-benchmark",
  "level-test",
  "deps/ui/ui-proc-test",
]

resolver = "2"

[workspace.metadata.cargo-machete]
ignored = []

[workspace.dependencies]
android_logger = "0.14"
anyhow = "1.0"
bytemuck = { version = "1.15", features = ["derive"] }
cfg_aliases = "0.2"
chrono = "0.4"
convert_case = "0.6"
dirs = "5.0"
educe = "0.6.0"
env_logger = "0.11"
fake = "2.9.2"
home = "0.5"
image = "0.25"
log = "0.4"
nonempty = "0.10.0"
quote = "1.0"
rand = "0.8"
rapier2d = { version = "0.22.0", features = ["simd-nightly"] }
#rapier2d = { version = "0.20.0", features = ["enhanced-determinism"] }
# rapier2d = { version = "0.20.0", features = ["parallel", "simd-stable"] }
aes-gcm = "0.10.3"
indexmap = "2.2"
lyon = "1.0"
rodio = "0.19.0"
rust_decimal = "1.35"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serial_test = "3.1"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls"] }
syn = { version = "2.0", features = ["full", "extra-traits"] }
tokio = { version = "1.38.0", features = ["full"] }
walkdir = "2.5"
web-time = "1.0.0"

glyph_brush = "0.7.8"
wgpu = "22.1.0"
wgpu_text = "0.9.0"
winit = "0.30.5"

jni = "0.21.1"
manage = "=0.6.0"
reflected = "=0.10.1"
refs = { version = "=0.11.0", default-features = true }
vents = "=0.6.0"

audio = { path = "deps/audio" }
call-counter = { path = "deps/call-counter" }
dispatch = { path = "deps/dispatch" }
gen = { path = "deps/gen" }
gm = { path = "deps/gm" }
image-proc = { path = "deps/wgpu-wrapper/image-proc" }
level = { path = "deps/level" }
level-proc = { path = "deps/level/level-proc" }
store = { path = "deps/store" }
test-engine = { path = "test-engine" }
test-game = { path = "test-game" }
ui = { path = "deps/ui" }
ui-benchmark = { path = "ui-benchmark" }
ui-proc = { path = "deps/ui/ui-proc" }
utils = { path = "deps/utils" }
valid = { path = "deps/valid" }
wgpu-wrapper = { path = "deps/wgpu-wrapper" }


[patch.crates-io]
#wgpu = { git = "https://github.com/VladasZ/wgpu", rev = "31ef1f08d238c2a092be1186f7133f1928b34a8a" }
#wgpu = { path = "../3/wgpu/wgpu" }
#vents = { path = "../deps/vents/vents" }
#reflected = { path = "../deps/reflected/reflected" }
#tain = { path = "../deps/tain/tain" }
#wgpu_text = { git = "https://github.com/VladasZ/wgpu-text", rev = "55c4d955baae1c44c3336ff9ad5e671f561cf65e" }
