[package]
name = "test_engine"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "test_engine_lib"
crate-type = ["staticlib"]

[[bin]]
name = "test_engine"

[dependencies]
gl = "0.14.0"
rand = "0.8.3"
regex = "1.4.5"
guard = "0.5.0"
cfg-if = "1.0.0"
fontdue = "0.4.0"
num-traits = "0.2.14"

[target.'cfg(not(target_os="ios"))'.dependencies]
glfw = "0.41.0"
freetype-sys = "0.14.0"

soil2 = { git = "https://github.com/VladasZ/soil2",  branch = 'main' }
 