[package]
name = "test_game"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[[bin]]
name = "test_game"

[lib]
name = "test_game_lib"
crate-type = ["rlib", "staticlib", "dylib"]

[dependencies]
log = { version = "0.4", features = ["kv_unstable"] }
tokio = { version = "1.15", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }


test_engine = { path = "test_engine" }

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.11"
android-ndk-sys = "0.2"

[build-dependencies]
cfg_aliases = "0.1"
