[package]
name = "dispatch"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "dispatch"
crate-type = ["rlib", "staticlib"]

[dependencies]
rtools = "0.1.21"
tokio = { version = "1.21", features = ["full"] }
