[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "dispatch"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "dispatch"

[dependencies]
log = { workspace = true }
tokio = { workspace = true }

refs = { workspace = true }
rtools = { workspace = true }
