[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "test-game"
version = "0.1.0"

[[bin]]
name = "test-game"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]
name = "test_game_lib"

[dependencies]
tokio = { workspace = true }

test-engine = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }

[package.metadata.android]
build_targets = ["armv7-linux-androideabi", "aarch64-linux-android"]
min_sdk_version = 23
target_sdk_version = 29
