[package]
name = "gm"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "gm"
crate-type = ["rlib", "staticlib"]

[dependencies]
rand = "0"
serde = { version = "1", features = ["derive"] }
tools = { path = "../.rdeps/tools" }
