[package]
name = "gm"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "gm"
crate-type = ["rlib", "staticlib"]

[dependencies]
rand = "0.8.3"
tools = { path = "../.rdeps/tools" }

