[package]
name = "gm"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "gm"
crate-type = ["rlib", "staticlib"]

[dependencies]
rand = "0.8.3"
serde = { version = "1.0.130", features = ["derive"] }
tools = { path = "../.rdeps/tools" }
