[package]
edition = "2021"
name = "ui_views"
version = "0.1.0"

[dependencies]
chrono = { workspace = true }
derivative = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
smart-default = { workspace = true }
tokio = { workspace = true }

dispatch = { workspace = true }
gm = { workspace = true }
manage = { workspace = true }
reflected = { workspace = true }
refs = { workspace = true }
rtools = { workspace = true }
ui = { workspace = true }
wgpu_wrapper = { workspace = true }


[dev-dependencies]
serial_test = { workspace = true }
