[package]
name = "ui_views"
version = "0.1.0"
edition = "2021"

[dependencies]
refs = "0.1.3"
rtools = "0.1.7"
smart-default = "0.6"

ui = { path = ".." }
#ui_proc = { path = "../ui_proc" }

gm = { path = "../../gm" }
text = { path = "../../text" }
gl_image = { path = "../../gl_image" }
gl_wrapper = { path = "../../gl_wrapper" }
