[package]
edition = "2021"
name    = "ui_views"
version = "0.1.0"

[dependencies]
reflected     = { workspace = true }
refs          = { workspace = true }
rtools        = { workspace = true }
smart-default = { workspace = true }
tokio         = { workspace = true }

ui = { workspace = true }

dispatch   = { workspace = true }
gl_image   = { workspace = true }
gl_wrapper = { workspace = true }
gm         = { workspace = true }
text       = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
