[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name    = "gl_image"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name       = "gl_image"

[dependencies]
image = "0.24"

log    = { workspace = true }
refs   = { workspace = true }
rtools = { workspace = true }

gl_wrapper = { workspace = true }
gm         = { workspace = true }
