[package]
name = "gl_image"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "gl_image"
crate-type = ["rlib", "staticlib"]

[dependencies]
log = "0.4"
image = "0.23"
cfg-if = "1.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }


gm = { path = "../gm" }
rtools = { path = "../rtools" }
gl_wrapper = { path = "../gl_wrapper" }
