[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "audio"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "audio"

[dependencies]
cfg-if = { workspace = true }
rtools = { workspace = true }

rodio = "0.17"

[build-dependencies]
cfg_aliases = { workspace = true }
