[package]
name = "audio"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "audio"
crate-type = ["rlib", "staticlib"]

[dependencies]
rodio = "0.15"

rtools = { path = "../../rtools" }