[package]
name = "ui"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "ui"
crate-type = ["rlib", "staticlib"]

[dependencies]
log = "0.4"
derivative = "2.2"
smart-default = "0.6"

gm = { path = "../gm" }
text = { path = "../text" }
rtools = { path = "../rtools" }
ui_proc = { path = "ui_proc" }
gl_image = { path = "../gl_image" }
gl_wrapper = { path = "../gl_wrapper" }

[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = "0.14"
glfw = "0.43"

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
mashup = "0.1"
gles31-sys = { path = "../../gles31-sys" }

[build-dependencies]
cfg_aliases = "0.1"
