[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "ui"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
doctest = false
name = "ui"

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
derivative = { workspace = true }
dispatch = { workspace = true }
refs = { workspace = true }
nonempty = { workspace = true }
rtools = { workspace = true }
rust_decimal = { workspace = true }
itertools = { workspace = true }
vents = { workspace = true }
reflected = { workspace = true }

gl_wrapper = { workspace = true }
gm = { workspace = true }
ui_proc = { workspace = true }

[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = { workspace = true }
glfw = { workspace = true }

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
gles31-sys = { workspace = true }
mashup = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }
