[package]
name = "net"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
refs = "0.1.6"
rtools = "0.1.8"
serde_json = "1.0"

serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }

dispatch = { path = "../dispatch" }
