[package]
name = "net"
version = "0.1.0"
edition = "2021"

[dependencies]
tao-log = "1.0"
serde_json = "1.0"

serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }

rtools = { path = "../rtools" }