[package]
edition = "2021"
name = "rest"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
