[package]
edition = "2021"
name    = "rest"
version = "0.1.0"

[dependencies]
actix-web  = "4"
log        = { workspace = true }
reqwest    = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde      = { workspace = true }
serde_json = { workspace = true }

rtools = { workspace = true }
