[package]
name = "rest"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
rtools = "0.1.28"
actix-web = "4"
serde_json = "1.0"

serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
