[package]
name = "text"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "text"
crate-type = ["rlib", "staticlib"]

[dependencies]
log = "0.4"
refs = "0.1.25"
rtools = "0.1.28"
fontdue = "0.7"

gm = { path = "../gm" }
gl_image = { path = "../gl_image" }

[dev-dependencies]
serial_test = "0.9.0"
