[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "wgpu_wrapper"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "wgpu_wrapper"

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
env_logger = { workspace = true }
gl_wrapper = { workspace = true }
image = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
glyph_brush = { workspace = true }

manage = { workspace = true }
refs = { workspace = true }
rtools = { workspace = true }

gm = { workspace = true }
