[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "scene"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "scene"

[dependencies]
cgmath = { workspace = true }
gm = { workspace = true }
