[package]
name = "proc_macro"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "proc_macro"
proc-macro = true

[dependencies]
syn = "1.0.74"
quote = "1.0.9"
