[package]
name = "test_game"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[[bin]]
name = "test_game"

[lib]
name = "test_game"
crate-type = ["rlib", "staticlib", "dylib"]

[dependencies]
log = "0.4"
serde_json = "1.0"
gl_wrapper = { path = "../gl_wrapper" }
test_engine = { path = "../test_engine" }

rtools = { path = "../rtools" }

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.10"
android-ndk-sys = "0.2"