[package]
name = "test_game"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[[bin]]
name = "test_game"

[lib]
name = "test_game"
crate-type = ["rlib", "staticlib", "dylib"]

[dependencies]
log = "0"
serde_json = "1"
gl_wrapper = { path = "../gl_wrapper" }
test_engine = { path = "../test_engine" }

tools = { path = "../.rdeps/tools" }

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0"
android-ndk-sys = "0"