[package]
name = "test_game"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[[bin]]
name = "test_game"

[lib]
name = "test_game"
crate-type = ["rlib", "staticlib", "dylib"]

[dependencies]
log = "0.4.14"
serde_json = "1.0.68"
gl_wrapper = { path = "../gl_wrapper" }
test_engine = { path = "../test_engine" }

tools = { path = "../.rdeps/tools" }

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19", default-features = false }
android_logger = "0.10"
