[package]
name = "sprites"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "sprites"
crate-type = ["rlib", "staticlib"]

[dependencies]
refs = "0.1.17"
vents = "0.1.5"
rtools = "0.1.12"
crossbeam = "0.8"
smart-default = "0.6"
rapier2d = { version = "0.14", features = [ "parallel", "simd-stable" ] }

gm = { path = "../gm" }
gl_image = { path = "../gl_image" }
