[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "sprites"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "sprites"

[dependencies]
anyhow = { workspace = true }
#crossbeam = "0.8.2"
gl_image = { workspace = true }
gl_wrapper = { workspace = true }
gm = { workspace = true }
rapier2d = { workspace = true }
refs = { workspace = true }
rtools = { workspace = true }
smart-default = { workspace = true }
vents = { workspace = true }
