[package]
name = "maze"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "maze"
crate-type = ["rlib", "staticlib"]

[dependencies]
tokio = "1.15"

gm = { path = "../gm" }
rtools = { path = "../rtools" }

rand = "0.8"
