[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "gl_wrapper"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "gl_wrapper"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
smart-default = { workspace = true }

refs = { workspace = true }
rtools = { workspace = true }
vents = { workspace = true }

gm = { workspace = true }

[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = { workspace = true }
glfw = { workspace = true }

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
gles31-sys = { workspace = true }
mashup = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }
