[package]
name = "gl_wrapper"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"

[lib]
name = "gl_wrapper"
crate-type = ["rlib", "staticlib"]

[dependencies]
log = "0.4"
vents = "0.1.5"
rtools = "0.1.27"
cfg-if = "1.0"

gm = { path = "../gm" }

[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
gl = "0.14"
glfw = "0.45"

[target.'cfg(any(target_os="ios", target_os="android"))'.dependencies]
mashup = "0.1"
gles31-sys = { path = "../../gles31-sys" }

[build-dependencies]
cfg_aliases = "0.1"
