[package]
name = "sprites"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "sprites"
crate-type = ["rlib", "staticlib"]

[dependencies]
rapier2d = { version = "0.9.2", features = [ "parallel", "simd-stable" ] }

gm = { path = "../gm" }
gl_image = { path = "../gl_image" }
proc_macro = { path = "../proc_macro" }

tools = { path = "../.rdeps/tools" }

[target.'cfg(not(any(target_os="ios", target_os="android")))'.dependencies]
glfw = "0.41.0"
