[package]
name = "sprites"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[lib]
name = "sprites"
crate-type = ["rlib", "staticlib"]

[dependencies]
#rand = "0.8.3"

#fontdue = "0.4.0"
#
gm = { path = "../gm" }
gl_image = { path = "../gl_image" }
tools = { path = "../.rdeps/tools" }
rapier2d = { version = "0.9.2", features = [ "parallel", "simd-stable" ] }


