[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "gen"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "gen"

[dependencies]
tokio = { workspace = true }

gm = { workspace = true }
rtools = { workspace = true }
