name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  ANDROID_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: android
        run: python3 build.py android
      - name: debo
        run: |
          echo kwak
          echo /usr/local/lib/android/sdk/ndk/22.1.7171670
          ls /usr/local/lib/android/sdk/ndk/22.1.7171670
          echo /usr/local/lib/android/sdk/ndk/22.1.7171670/prebuilt
          ls /usr/local/lib/android/sdk/ndk/22.1.7171670/prebuilt