name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  ANDROID_BUILD: true
  NDK_HOME: ${ANDROID_HOME}/ndk/22.1.7171670/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: android
        run: python3 build.py android