name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        target: [
          { runner: mac, os: macos },
          { runner: lin, os: linux },
          { runner: windows-latest, os: windows },
#          { runner: rpi, os: raspberry },

          { runner: mac, os: ios },
          { runner: ubuntu-latest, os: android }
        ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive
          
      - name: Build
        if: ${{ matrix.target.os != 'windows' }}
        run: ./build/build.sh ${{ matrix.target.os }}

      - name: Build windows
        if: ${{ matrix.target.os == 'windows' }}
        run: py build/build.py

      - name: Test
        run: cargo test --all
