name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        target: [
          # { runner: mac, os: macos },
          { runner: lin, os: linux },
          { runner: ubuntu-latest, os: linux },
          # { runner: win, os: windows },
          # { runner: ARM64, os: raspberry },

          # { runner: mac, os: ios },
          # { runner: lin, os: android }
        ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive
      - name: build
        run: python3 build.py ${{ matrix.target.os }}