name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        target: [
          # { runner: mac, os: macos },
          { runner: lin, os: linux },
          # { runner: win, os: windows },
          # { runner: ARM64, os: raspberry },

          # { runner: mac, os: ios },
          # { runner: lin, os: android }
        ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive

      # - name: Install rustup
      #   run: |
      #     echo Installing rustup:
      #     curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Build
        run: ./build.sh ${{ matrix.target.os }}

      # - name: Build
      #   run: |
      #     source "$HOME/.cargo/env"
      #     python3 build.py ${{ matrix.target.os }}