name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  desktop:
    strategy:
      matrix:
        os: [macOS, ubuntu-latest, windows-latest, ARM64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive
      - name: build
        run: python3 build.py

  mobile:
    strategy:
      matrix:
        target: [ { runner: macOS, os: ios }, { runner: ubuntu-latest, os: android } ]
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive
      - name: build
        run: python3 build.py ${{ matrix.target.os }}