name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      matrix:
        target: [
          { runner: macOS, os: macos },
          { runner: ubuntu-latest, os: linux },
          { runner: windows-latest, os: windows },

          { runner: macOS, os: ios },
          { runner: ubuntu-latest, os: android }
        ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: recursive
      - name: build
        run: python3 build.py ${{ matrix.target.os }}