name: Raspberry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ARM64
    strategy:
      matrix:
        arch:
          - arm64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: linux arm
        run: python3 build.py
