name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

    linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: linux
          run: |
            sudo apt install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev xorg-dev
            cargo build --verbose

    macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: macos
          run: |
            cargo build --verbose

    windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: windows
          run: |
            cargo build --verbose